name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build Plugin
        run: ./gradlew initProject buildFlintPlugin
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Build IDE
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: ./gradlew buildFlintIde
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            TODO Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      - name: Upload Plugin
        id: upload_plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./code/build/artifacts/FlintPluginDistribution/Flint.zip
          asset_name: flint-plugin.zip
          asset_content_type: application/zip
      - name: Upload MacOS IDE
        id: upload_macos_ide
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./code/build/artifacts/FlintIdeDistribution/Flint.macos.zip
          asset_name: flint-macos-ide.zip
          asset_content_type: application/zip
      - name: Upload Windows IDE
        id: upload_win_ide
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./code/build/artifacts/FlintIdeDistribution/Flint.win.zip
          asset_name: flint-win-ide.zip
          asset_content_type: application/zip
      - name: Upload Linux IDE
        id: upload_linux_ide
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./code/build/artifacts/FlintIdeDistribution/Flint.tar.gz
          asset_name: flint-linux-ide.tar.gz
          asset_content_type: application/gzip
